# Generated by Django 4.2.7 on 2025-11-18 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام دسر')),
                ('category', models.CharField(choices=[('noraml', 'عادی'), ('hazrati ', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دسر',
                'verbose_name_plural': 'دسرها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام غذا')),
                ('category', models.CharField(choices=[('noraml', 'عادی'), ('hazrati ', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی')),
                ('meal_type', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نوع غذا')),
                ('preparation_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='زمان آماده سازی')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_serving', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار برای هر سرو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='foods.food', verbose_name='غذا')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_usages', to='ingredients.ingredient', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'مواد اولیه غذا',
                'verbose_name_plural': 'مواد اولیه غذاها',
                'ordering': ['food'],
            },
        ),
    ]
