# Generated by Django 4.2.20 on 2025-12-07 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_alter_dessert_category_alter_food_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="dessert",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("needy", "نیازمندان"),
                    ("ceremonies", "مراسمات"),
                    ("honorary", "تکریمی"),
                    ("lottery", "قرعه کشی"),
                    ("participatory_camps", "اردوهای مشارکتی"),
                    ("staff", "پرسنل"),
                    ("sales", "فروشی"),
                ],
                default="needy",
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="زیر دسته بندی",
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("needy", "نیازمندان"),
                    ("ceremonies", "مراسمات"),
                    ("honorary", "تکریمی"),
                    ("lottery", "قرعه کشی"),
                    ("participatory_camps", "اردوهای مشارکتی"),
                    ("staff", "پرسنل"),
                    ("sales", "فروشی"),
                ],
                default="needy",
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="زیر دسته بندی",
            ),
        ),
        migrations.RunSQL(
            # Update existing records based on their category
            sql=[
                "UPDATE foods_food SET subcategory = 'needy' WHERE category = 'hazrati' AND subcategory = 'needy';",
                "UPDATE foods_food SET subcategory = 'participatory_camps' WHERE category = 'noraml' AND subcategory = 'needy';",
                "UPDATE foods_dessert SET subcategory = 'needy' WHERE category = 'hazrati' AND subcategory = 'needy';",
                "UPDATE foods_dessert SET subcategory = 'participatory_camps' WHERE category = 'noraml' AND subcategory = 'needy';",
            ],
            reverse_sql=[
                "UPDATE foods_food SET subcategory = 'needy';",
                "UPDATE foods_dessert SET subcategory = 'needy';",
            ],
        ),
    ]
