# Generated by Django 4.2.20 on 2025-12-07 12:41

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_dessert_subcategory_food_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=timezone.now, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.RunSQL(
            # Update existing records with current timestamp
            sql=[
                "UPDATE foods_food SET created_at = NOW() WHERE created_at IS NULL;",
                "UPDATE foods_food SET updated_at = NOW() WHERE updated_at IS NULL;",
            ],
            reverse_sql=[
                "UPDATE foods_food SET created_at = NULL;",
                "UPDATE foods_food SET updated_at = NULL;",
            ],
        ),
        migrations.AlterField(
            model_name="food",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="dessert",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("needy", "نیازمندان"),
                    ("ceremonies", "مراسمات"),
                    ("honorary", "تکریمی"),
                    ("lottery", "قرعه کشی"),
                    ("participatory_camps", "اردوهای مشارکتی"),
                    ("staff", "پرسنل"),
                    ("sales", "فروشی"),
                ],
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="زیر دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("needy", "نیازمندان"),
                    ("ceremonies", "مراسمات"),
                    ("honorary", "تکریمی"),
                    ("lottery", "قرعه کشی"),
                    ("participatory_camps", "اردوهای مشارکتی"),
                    ("staff", "پرسنل"),
                    ("sales", "فروشی"),
                ],
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="زیر دسته بندی",
            ),
        ),
    ]
