# Generated by Django 4.2.20 on 2025-12-07 13:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_food_created_at_food_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dessert",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="dessert",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="foodingredient",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="foodingredient",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
    ]
