# Generated by Django 4.2.7 on 2025-12-21 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_created_at_alter_food_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.CharField(choices=[('normal', 'عادی'), ('hazrati', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('normal', 'عادی'), ('hazrati', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی'),
        ),
    ]
