# Generated by Django 4.2.20 on 2025-12-31 06:14

from django.db import migrations, models
import django.contrib.postgres.fields


def convert_meal_type_to_meal_types(apps, schema_editor):
    """Convert meal_type to meal_types (list)"""
    Food = apps.get_model('foods', 'Food')
    # Use raw SQL to get meal_type value since we need to access it before removal
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, meal_type FROM foods_food WHERE meal_type IS NOT NULL")
        rows = cursor.fetchall()
        for food_id, meal_type in rows:
            Food.objects.filter(id=food_id).update(meal_types=[meal_type])


def reverse_convert_meal_types_to_meal_type(apps, schema_editor):
    """Reverse: Convert meal_types (list) back to meal_type (first item) - not fully reversible"""
    # This is a one-way migration, reverse is not fully supported
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0007_alter_dessert_category_alter_food_category"),
    ]

    operations = [
        # First, add the new field
        migrations.AddField(
            model_name="food",
            name="meal_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=50),
                default=list,
                help_text='وعده\u200cهای غذایی (می\u200cتوانید چند مورد را انتخاب کنید)',
                size=None,
                verbose_name="نوع غذا",
            ),
        ),
        # Data migration: Convert meal_type to meal_types
        migrations.RunPython(
            code=convert_meal_type_to_meal_types,
            reverse_code=reverse_convert_meal_types_to_meal_type,
        ),
        # Now remove the old field
        migrations.RemoveField(
            model_name="food",
            name="meal_type",
        ),
    ]
