# Generated by Django 4.2.7 on 2025-11-06 06:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام مرکز')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'مرکز',
                'verbose_name_plural': 'مراکز',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['center', 'name'], 'verbose_name': 'رستوران', 'verbose_name_plural': 'رستوران\u200cها'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام رستوران'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='center',
            field=models.ForeignKey(blank=True, help_text='مرکز مربوط به این رستوران', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.center', verbose_name='مرکز'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('center', 'name')},
        ),
    ]
