# Generated by Django 4.2.7 on 2025-11-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_data_migration_default_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='center',
            field=models.ForeignKey(help_text='مرکز مربوط به این رستوران', on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.center', verbose_name='مرکز'),
        ),
    ]
