# Generated by Django 4.2.7 on 2025-11-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0005_alter_restaurant_center'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrestaurantpermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='userrestaurantpermission',
            name='user',
            field=models.OneToOneField(help_text='هر کاربر فقط می\u200cتواند به یک رستوران متصل باشد', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_permission', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
