# Generated by Django 4.2.20 on 2025-12-23 18:33

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_directsale_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directsale",
            name="date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ"
            ),
        ),
        migrations.AddField(
            model_name="directsale",
            name="sale_code",
            field=models.CharField(
                default="asd",
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="کد فروش",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="directsale",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="قیمت کل",
            ),
        ),
    ]
