# Generated by Django 4.2.7 on 2025-12-23 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_directsale_date_directsale_sale_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsale',
            name='sale_code',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='کد فروش'),
        ),
    ]
