# Generated by Django 4.2.7 on 2025-11-18 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('meal_type', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نوع غذا')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ظرفیت')),
                ('dessert_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد دسر')),
                ('cook_status', models.CharField(choices=[('pending', 'در انتظار'), ('cooking', 'در حال پخت'), ('done', 'پخته شده')], default='pending', max_length=50, verbose_name='وضعیت پخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_plans', to='foods.dessert', verbose_name='دسر')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_plans', to='foods.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'برنامه غذایی',
                'verbose_name_plural': 'برنامه\u200cهای غذایی',
                'ordering': ['-date', 'meal_type'],
            },
        ),
    ]
