# Generated by Django 4.2.7 on 2025-11-06 06:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام رستوران')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_central',
            field=models.BooleanField(default=False, help_text='کاربران مرکزی به تمام رستوران\u200cها و دسترسی\u200cها دسترسی دارند', verbose_name='کاربر مرکزی'),
        ),
        migrations.CreateModel(
            name='UserRestaurantPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list, help_text='لیست نقش\u200cهای دسترسی کاربر در این رستوران', verbose_name='نقش\u200cهای دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='accounts.restaurant', verbose_name='رستوران')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_permissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی کاربر به رستوران',
                'verbose_name_plural': 'دسترسی\u200cهای کاربران به رستوران\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
