# Generated by Django 4.2.7 on 2025-11-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_user_is_central_userrestaurantpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
