# Generated by Django 4.2.7 on 2025-11-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_restaurant_name_remove_user_roles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrestaurantpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrestaurantpermission',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='userrestaurantpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='UserRestaurantPermission',
        ),
    ]
