# Generated by Django 4.2.20 on 2025-11-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userrestaurantpermission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="لیست نقش\u200cهای دسترسی کاربر",
                verbose_name="نقش\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_central",
            field=models.BooleanField(
                default=False,
                help_text="کاربران مرکزی به تمام دسترسی\u200cها دسترسی دارند",
                verbose_name="کاربر مرکزی",
            ),
        ),
    ]
