# Generated by Django 4.2.7 on 2025-11-18 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='توکن')),
                ('customer_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام مشتری')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='تلفن مشتری')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'توکن',
                'verbose_name_plural': 'توکن\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_items', to='foods.food', verbose_name='غذا')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tokens.token', verbose_name='توکن')),
            ],
            options={
                'verbose_name': 'آیتم توکن',
                'verbose_name_plural': 'اقلام توکن',
                'ordering': ['created_at'],
            },
        ),
    ]
