# Generated by Django 4.2.20 on 2025-12-07 13:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="date",
            field=django_jalali.db.models.jDateField(verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="token",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="tokenitem",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="tokenitem",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
    ]
