# Generated by Django 4.2.20 on 2025-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_alter_token_created_at_alter_token_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="status",
            field=models.CharField(
                choices=[("pending", "در انتظار دریافت"), ("received", "دریافت شده")],
                default="pending",
                max_length=50,
                verbose_name="وضعیت",
            ),
        ),
    ]
