# Generated by Django 4.2.20 on 2025-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_token_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenitem",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "صبحانه"),
                    ("lunch", "ناهار"),
                    ("dinner", "شام"),
                ],
                default="lunch",
                help_text="وعده غذایی که این آیتم برای آن صادر شده است",
                max_length=50,
                verbose_name="وعده غذایی",
            ),
        ),
    ]
