# Generated by Django 4.2.7 on 2025-11-18 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('noraml', 'عادی'), ('hazrati ', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='نام ماده اولیه')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('mg', 'میلی\u200cگرم'), ('ton', 'تن'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('cup', 'پیمانه / لیوان'), ('tbsp', 'قاشق غذاخوری'), ('tsp', 'قاشق چای\u200cخوری'), ('pcs', 'عدد'), ('pack', 'بسته'), ('carton', 'کارتن'), ('dozen', 'شل / دوجین'), ('set', 'دست / مجموعه'), ('tray', 'سینی'), ('bag', 'کیسه / گونی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='واحد')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('code', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='کد')),
                ('warning_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار هشدار موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار موجودی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='ingredients.ingredient', verbose_name='ماده اولیه')),
            ],
            options={
                'verbose_name': 'موجودی ماده اولیه',
                'verbose_name_plural': 'موجودی مواد اولیه',
                'ordering': ['ingredient'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='تغییر موجودی')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('mg', 'میلی\u200cگرم'), ('ton', 'تن'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('cup', 'پیمانه / لیوان'), ('tbsp', 'قاشق غذاخوری'), ('tsp', 'قاشق چای\u200cخوری'), ('pcs', 'عدد'), ('pack', 'بسته'), ('carton', 'کارتن'), ('dozen', 'شل / دوجین'), ('set', 'دست / مجموعه'), ('tray', 'سینی'), ('bag', 'کیسه / گونی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='واحد')),
                ('code', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='کد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ingredients.inventorystock', verbose_name='موجودی ماده اولیه')),
            ],
            options={
                'verbose_name': 'لاگ موجودی ماده اولیه',
                'verbose_name_plural': 'لاگ\u200cهای موجودی مواد اولیه',
                'ordering': ['-created_at'],
            },
        ),
    ]
