# Generated by Django 4.2.7 on 2025-11-21 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('noraml', 'عادی'), ('hazrati', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی'),
        ),
    ]
