# Generated by Django 4.2.7 on 2025-12-03 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('mg', 'میلی\u200cگرم'), ('ton', 'تن'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('cup', 'پیمانه / لیوان'), ('tbsp', 'قاشق غذاخوری'), ('tsp', 'قاشق چای\u200cخوری'), ('pcs', 'عدد'), ('pack', 'بسته'), ('carton', 'کارتن'), ('dozen', 'شل / دوجین'), ('set', 'دست / مجموعه'), ('tray', 'سینی'), ('bag', 'کیسه / گونی')], max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='واحد'),
        ),
    ]
