# Generated by Django 4.2.7 on 2025-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('g', 'گرم'), ('mg', 'میلی\u200cگرم'), ('ton', 'تن'), ('l', 'لیتر'), ('ml', 'میلی\u200cلیتر'), ('cup', 'پیمانه / لیوان'), ('tbsp', 'قاشق غذاخوری'), ('tsp', 'قاشق چای\u200cخوری'), ('pcs', 'عدد'), ('pack', 'بسته'), ('carton', 'کارتن'), ('dozen', 'شل / دوجین'), ('set', 'دست / مجموعه'), ('tray', 'سینی'), ('bag', 'کیسه / گونی')], max_length=150, verbose_name='واحد'),
        ),
    ]
