# Generated by Django 4.2.20 on 2025-12-07 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0006_ingredient_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="subcategory",
            field=models.CharField(
                choices=[
                    ("needy", "نیازمندان"),
                    ("ceremonies", "مراسمات"),
                    ("honorary", "تکریمی"),
                    ("lottery", "قرعه کشی"),
                    ("participatory_camps", "اردوهای مشارکتی"),
                    ("staff", "پرسنل"),
                    ("sales", "فروشی"),
                ],
                max_length=150,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="زیر دسته بندی",
            ),
        ),
    ]
