# Generated by Django 4.2.20 on 2025-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0007_alter_ingredient_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ تحویل"),
        ),
    ]
