# Generated by Django 4.2.20 on 2025-12-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0008_inventorylog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorystock",
            name="last_received_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاریخ آخرین تحویل"
            ),
        ),
    ]
