# Generated by Django 4.2.20 on 2025-12-07 13:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0009_inventorystock_last_received_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تحویل"
            ),
        ),
        migrations.AlterField(
            model_name="inventorylog",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="inventorystock",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="inventorystock",
            name="last_received_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ آخرین تحویل"
            ),
        ),
        migrations.AlterField(
            model_name="inventorystock",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
    ]
