# Generated by Django 4.2.7 on 2025-12-21 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_alter_ingredient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('normal', 'عادی'), ('hazrati', 'حضرتی')], max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='دسته بندی'),
        ),
    ]
